# Generated by Django 5.2 on 2026-03-26 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
        ('mascota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialadopcion',
            name='adopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='adopcion.adopcion'),
        ),
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'APROBADO')), fields=('mascota',), name='unique_active_adopcion_por_mascota'),
        ),
    ]
