# Generated by Django 5.2 on 2026-03-26 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
        ('fundacion', '0003_remove_fundacion_direccion'),
        ('usuario', '0002_remove_usuario_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_fundacion', to='fundacion.fundacion'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_usuario', to='usuario.usuario'),
        ),
    ]
