# Generated by Django 5.2 on 2026-03-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundacion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacionmiembro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='miembros',
            field=models.ManyToManyField(related_name='fundaciones', through='fundacion.FundacionMiembro', to='usuario.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='fundacionmiembro',
            unique_together={('fundacion', 'usuario')},
        ),
    ]
