# Generated by Django 5.2 on 2026-03-26 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0001_initial'),
        ('fundacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microchip', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('patron_color', models.CharField(max_length=50)),
                ('sociable', models.BooleanField(default=False)),
                ('actividad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedicoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esterilizado', models.BooleanField(default=False)),
                ('tratamiento', models.BooleanField(default=False)),
                ('observacion_tratamiento', models.TextField()),
                ('vacunas', models.BooleanField(default=False)),
                ('observacion_vacuna', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ADOPTADO', 'Adoptado'), ('EN_REVISION', 'En revisión')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='mascota.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='RazaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.especiemascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.razamascota'),
        ),
        migrations.CreateModel(
            name='UbicacionMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direccion.direccion')),
                ('fundacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundacion.fundacion')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='mascota.mascota')),
            ],
        ),
    ]
