# Generated by Django 5.2 on 2026-03-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionmascota',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionmascota',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('mascota',), name='unique_active_ubicacion_por_mascota'),
        ),
    ]
