# Generated by Django 5.2 on 2026-03-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmedicomascota',
            name='updated_at',
        ),
    ]
