# Generated by Django 5.2 on 2026-04-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_remove_historialmedicomascota_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomascota',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptado', 'Adoptado'), ('En revisión', 'En revisión')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='actividad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=50),
        ),
    ]
