# Generated by Django 5.2 on 2026-04-01 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_alter_estadomascota_estado_alter_mascota_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadomascota',
            name='fecha_cambio',
        ),
        migrations.AlterField(
            model_name='estadomascota',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota'),
        ),
        migrations.AlterField(
            model_name='ubicacionmascota',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota'),
        ),
    ]
